version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./docker/nginx/config:/etc/nginx/conf.d
            #- ./docker/nginx/certs:/etc/nginx/certs
            - ./public:/var/www/html/public:cached
        links:
            - php
        networks:
            - dumbel
    php:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./app/:/var/www/html/app
            - ./bootstrap/:/var/www/html/bootstrap
            - ./config/:/var/www/html/config
            - ./database/:/var/www/html/database
            - ./public/:/var/www/html/public
            - ./resources/:/var/www/html/resources
            - ./routes/:/var/www/html/routes
            - ./storage/:/var/www/html/storage
            - ./vendor/:/var/www/html/vendor
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - ./artisan:/var/www/html/artisan
            - ./.env:/var/www/html/.env
        environment:
            - DB_HOST=${DB_HOST}
        links:
            - postgres
        networks:
            - dumbel
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        ports:
            - ${POSTGRESS_PORT}:5432
        restart: unless-stopped
        networks:
            - dumbel
    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080
        networks:
            - dumbel
    redis:
        image: redis:latest
        volumes:
            - ./docker/redis:/bitnami/redis/data
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - ${DOCKER_REDIS_PORT}:6379
        networks:
            - dumbel
volumes:
    postgres_data:
networks:
    dumbel:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.5.0/24