version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        ports:
            - "8000:80"
        working_dir: /var/www
        volumes:
            - ./public/:/var/www/public
        networks:
            - dumbel
        links:
            - app
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        hostname: dumbel-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./app/:/var/www/app
            - ./bootstrap/:/var/www/bootstrap
            - ./config/:/var/www/config
            - ./database/:/var/www/database
            - ./public/:/var/www/public
            - ./resources/:/var/www/resources
            - ./routes/:/var/www/routes
            - ./storage/:/var/www/storage
            - ./tests/:/var/www/tests
#            - ./vendor/:/var/www/vendor
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
            - ./artisan:/var/www/artisan
            - ./.env:/var/www/.env
            - ./.php-cs-fixer.php:/var/www/html/.php-cs-fixer.php
        environment:
            - DB_HOST=${DB_HOST}
        links:
            - postgres
        networks:
            - dumbel

    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        ports:
            - ${POSTGRESS_PORT}:5432
        restart: unless-stopped
        networks:
            - dumbel

    redis:
        image: redis:latest
        volumes:
            - ./docker/redis:/bitnami/redis/data
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - ${DOCKER_REDIS_PORT}:6379
        networks:
            - dumbel
volumes:
    postgres_data:
networks:
    dumbel:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.5.0/24