version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            #- ./docker/nginx/certs:/etc/nginx/certs
            - ./:/var/www/html
        links:
            - php

    php:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./docker/php-fpm/config/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/html
        environment:
            - DB_HOST=${DB_HOST}
        links:
            - postgres

    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${POSTGRESS_PORT}:5432
            - 6001:6001

    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080

    redis:
        image: redis:latest
        volumes:
            - ./docker/redis:/bitnami/redis/data
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - ${DOCKER_REDIS_PORT}:6379

volumes:
    postgres_data:
